# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_name: sarbideak
    department: '%env(DEPARTMENT_DEFAULT)%'
    contactEmail: '%env(CONTACT_EMAIL_DEFAULT)%'
    departmentDefault: '%env(DEPARTMENT_DEFAULT)%'
    contactEmailDefault: '%env(CONTACT_EMAIL_DEFAULT)%'

services:
    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']

    ldap:
        alias: Symfony\Component\Ldap\Ldap
            
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: '%env(LDAP_HOST)%'
                port: '%env(LDAP_PORT)%'
                encryption: none
                options:
                    protocol_version: 3
                    referrals: false    

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $siteId: '%env(SITE_ID)%'
            $limit: 50
            $saltoTokenUrl: '%env(SALTO_TOKEN_URL)%'
            $saltoApiBase: '%env(SALTO_API_BASE)%'
            $saltoApiUsername: '%env(SALTO_API_USERNAME)%'
            $saltoApiPassword: '%env(SALTO_API_PASSWORD)%'
            $saltoClientId: '%env(SALTO_CLIENT_ID)%'
            $saltoClientSecret: '%env(SALTO_CLIENT_SECRET)%'
            $department: '%department%'
            $contactEmail: '%contactEmail%'
            $departmentDefault: '%departmentDefault%'
            $contactEmailDefault: '%contactEmailDefault%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Importante priority must 100 or less
    App\EventListener\LocaleEventListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }